[package]
name = "png_writer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.6.5"
actix-files = "0.6.5"
actix-web = "4.5.1"
png = "0.17.11"
rand = "0.8.5"
